// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tgmxdnenkfjzbuthozbm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRnbXhkbmVua2ZqemJ1dGhvemJtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY2NTI2NTAsImV4cCI6MjA2MjIyODY1MH0.-_mIMzJIBT2BXIuvVPZkYjJVJQtDwzd9Cp-S8AUSk0I";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);